{{- if .Values.deployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-collector-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
data:
  collector.yaml: |
{{ tpl .Values.deployment.config . | indent 4 }}
{{- end }}
