{{- if .Values.deployment.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: otel-collector-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "otelCollector.name" . }}
      app.kubernetes.io/component: collector
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              telemetry-enabled: "true"
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "otelCollector.name" . }}
      ports:
        - port: 4317
        - port: 4318
        - port: 55680
{{- end }}
