{{- if .Values.daemonset.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.daemonset.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
{{ end }}
---
{{- if .Values.deployment.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
{{- end }}
