{{- if .Values.daemonset.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-otel-agent
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-otel-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-otel-agent
subjects:
  - kind: ServiceAccount
    name: {{ .Values.daemonset.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{- end }}
