apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kustomization.yaml
  - ../minio/deployment.yaml

patchesStrategicMerge:
  - loki-minio-patch.yaml
  - tempo-minio-patch.yaml
