app = "goblin-backend"

[build]
image = ""

[[services]]
internal_port = 8001
protocol = "tcp"

[services.concurrency]
type = "connections"
hard_limit = 25

[[services.ports]]
handlers = ["http"]
port = 80

[env]
PORT = "8001"

[deploy]
release_command = ""

[[mounts]]
source = "data"
destination = "/app/data"
