apiVersion: v2
name: argo-rollouts
description: A Helm chart for Argo Rollouts
type: application
version: 2.37.0
appVersion: "1.7.1"

dependencies:
  - name: argo-rollouts
    version: "2.37.0"
    repository: "https://argoproj.github.io/argo-helm"
