apiVersion: v2
name: kyverno
description: A Helm chart for Kyverno
type: application
version: 3.2.0
appVersion: "1.12.0"

dependencies:
  - name: kyverno
    version: "3.2.0"
    repository: "https://kyverno.github.io/kyverno/"
